# Dependencies
markdown:            redcarpet
highlighter:         pygments
markdown_ext:  markdown,mkdown,mkdn,mkd,md

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "with_toc_data", "fenced_code_blocks"]
  
# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               tester
tagline:             'BTech student at Malaviya National Institute of Technology'
description:         'Learn Improvise Innovate Repeat'
url:                 http://tester-1234.github.io
giturl:				 http://tester-1234.github.io
baseurl:             ""
paginate:            5
paginate_path:       "blog/page:num"
rss:                 atom.xml

# About/contact
author:
  name:             tester-1234

# Custom vars
version:             1.0.0

github:
  repo:           https://github.com/tester-1234/tester-1234.github.io
